version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_chatop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatop_db
      MYSQL_USER: chatop_user
      MYSQL_PASSWORD: chatop_pwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
